### ISSUE TITLE
How to configure the listening port?

### ISSUE THREAD

**Issue by lars18th** [zhyonc/sysproxy#1]
Hi,

The configuration of the UI is quite confusing. Please, try to improve these points:
- A box to configure the LISTENING port. When using the "http2socks5" (the main use of this tool, to HTTP-proxy using SSH), I can't do it. And the tool is using a (random?) port, i.e. 53600.
- The first colum, without name is annoying. I feel it represents the #ID of the rule, and it's ordered. If this is true, then please improve it.
- The software is detected as a potential backdoor by Chrome and Windows. I suggest to add the developer certificate to overcome this.

Regards.

**Comment by zhyonc** [comment]
@lars18th Thanks your test.
- Yes, the tool is using a random port when set "http2socks5", I could draw a box to set the listening port.
    - Now the system proxy is first node and the tool is second node so i assigned them the same of random port. 
    - But it seems you want a proxy chain? Your first node isn't system proxy and want the tool as the third, fourth...node?
- You are right, I forgot to set #ID on the first ceil.
- There may be some reasons caused the tool is detected:
    - The tool edits the registry value to set system proxy and auto-start.
    - Many viruses or malicious programs are written in go, which make the tool is detected more easliy.
    - ......
- You can temporarily add tool to your antivirus software's whitelist, I will try using a personal certificate to avoid detected.

**Comment by lars18th** [comment]
Thank you for your effort @zhyonc .

My suggestion, regarding the UI, is to make it the most simple for the user to set this use case: enable HTTP proxy over a SOCKS proxy using a SSH connection. Perhaps you'll want to add a HELP inside the README for this particulara user case. You agree?

**Comment by zhyonc** [comment]
@lars18th I think i can separate them into inbound tag and outbound tag.
- Inbound is system proxy set protocol is http/socks4/socks5/pac with forwardIP and forwardPort.
- Outbound is a forwarding station that convert the inboud protocol to your proxy core.
For example:
- If set inbound for system proxy:
```protocol=http forwardIP=127.0.0.1 forwardPort=8080```
- Follow outbound need to set:
```srcProtocol=http srcIP=127.0.0.1 srcPort=8080 and dstProtocol=socks5 dstIP=127.0.0.1 dstPort=1080```
So that you can forward http proxy over socks5 proxy.
If you don't need the system proxy, only need to set the outbound can forward any other http request.
At present, the above features only remains in conception.
The tool I developed before was only binding and forwarding the system proxy :)

**Comment by lars18th** [comment]
> @lars18th I think i can separate them into inbound tag and outbound tag.

That's a perfect solution. Clean and simple!

I'll wait impatiently for the new version. 😉

**Comment by zhyonc** [comment]
@lars18th Please try [0.1.1](https://github.com/zhyonc/sysproxy/releases/tag/0.1.1)

**Comment by zhyonc** [comment]
Hi, @lars18th, nice to hear you say it's working well. :smile:
- I used the "Inbound" and "Outbound" as models to design code, i don't agree to rename them to other names that make my code confusion.
- Menu items doesn't refresh tag name until setting form is closed. In other words: saving the config, refreshing tag name, selecting the last seleted tag will be done after the form is closed, not need to restart the program.
- The right-click icon pop-up menu item is the default behavior of the ui library, i found that the tray can set left-click function.
- Maybe I can trigger enable/disable switch for inbound and outbound when left-click tray icon:
  - Enable is restore the last selected index of inbound and outbound.
  - Disable is to select the "disable" tag name for both inbound and outbound.

**Comment by lars18th** [comment]
Hi @zhyonc ,

Thank you for the version 0.2.0. It work nice.

However, two comments to improve it a bit:
- Inside the README I suggest these changes:

---

### How to use
#### Inbound
The "inbound" setting represents the configuration of the System Proxy. Therefore the changes in this section will affect to all processes that uses the global Internet configuration.
- Click Setting menu item to open inbound form
...

#### Outbound
The "outbound" setting represents the different proxy configurations of this program. You can forward the Inbound to any of these proxies, or use directly them from any process configured to use it.
- Click Setting menu item to open outbound form
...

---

- Inside the README I recommend also to describe the functionality of the files `gfwlist.txt` and `pac.js`. We don't have any description about them.

Regards.

**Comment by lars18th** [comment]
Hi @zhyonc ,

> If I have time I will add the copy feature.

:+1:

> See [gfwlist](https://github.com/gfwlist/gfwlist) and [PAC](https://en.wikipedia.org/wiki/Proxy_auto-config)

I recommend that you put these links in the README to describe them. And regarding the GFWLIST file, perhaps you'll want to add the option to "use_it/don't_use". And then the tool could run without any `gfwlist` file. I understand the reason to support it, but I feel that not all users require to use it. What you think?
